name: PR Deployment
on: 
  pull_request

jobs:
  UnitsTests:
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test 

  E2ETests:
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize node node
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run e2e:run 

  Build:
    runs-on: ubuntu-22.04
    needs: [UnitsTests, E2ETests]
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize node node
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run build
