name: PR Deployment
on: 
  pull_request

jobs:
  UnitsTests:
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test 

  E2ETests:
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize node
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run e2e:run 

  Build:
    runs-on: ubuntu-22.04
    needs: [UnitsTests, E2ETests]
    permissions: 
      contents: write
      id-token: write
    environment: 
      name: github-pages
      url: ${{vars.PUBLIC_URL}}/
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize node
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Initialize deployment URL
        run: echo "PUBLIC_URL=${{vars.PUBLIC_URL}}/${{github.head_ref}}" >> $GITHUB_ENV

      - name: Run build
        run: npm run build

      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with: 
          folder: ./build
          target-folder: ${{github.head_ref}}
          clean: false
